In [4]:
import numpy as np
import pandas as pd

### CLEAN DATA

In [33]:
# movies_nc = pd.read_csv('movies.csv')
# movies_nc.head()

In [34]:
# clean_movie = movies_nc.copy()
# clean_movie['year'] = clean_movie.title.str.extract('(\d{4})')
# clean_movie['title'] = clean_movie.title.str.extract(r'^(.*?)\s*\(\d+\)$')

In [7]:
# clean_movie['genres'] = clean_movie.genres.str.split('|')
# for index, row in clean_movie.iterrows():
#     for genre in row.genres:
#         clean_movie.at[index, genre] = 1

# clean_movie = clean_movie.fillna(0)
# movies.head()

In [8]:
# clean_movie.to_csv('./clean_movie_df.csv')

In [9]:
movies = pd.read_csv('clean_movie_df.csv')
movies = movies.drop('Unnamed: 0', axis=1).reset_index(drop=True)
# movies.tail()

In [10]:
# movies.loc[movies.movieId==169]

In [11]:
rate = pd.read_csv('rating.csv')
# rate.head()

In [12]:
# for index, user in rate.head().iterrows():
#     print(f'user id {user.userId} rated {user.rating} to {movies[movies.movieId == user.movieId].title.values[0]}')

In [13]:
user_input = {
    'MovieName': ['Toy Story', 'Grumpier Old Men', 'Grand Slam'],
    'Rating': [5, 3.2, 3]
}
movie_input = pd.DataFrame(user_input)

In [14]:
movie_id = movies[movies['title'].isin(movie_input['MovieName'])]
movie_input = pd.merge(movie_id, movie_input, left_on='title', right_on='MovieName')
movie_input = movie_input.drop('MovieName', axis=1)
movie_input = movie_input.reset_index(drop=True)
# movie_input.head()

In [15]:
user_genres_table = movie_input.drop('title', axis=1).drop('genres', axis=1).drop('year', axis=1) \
.drop('movieId', axis=1).drop('Rating', axis=1)

In [25]:
weight_table = user_genres_table.transpose().dot(movie_input.Rating)

In [32]:
genres_table = movies.set_index(movies.movieId)
genres_table = genres_table.drop('title', axis=1).drop('genres', axis=1).drop('movieId', axis=1).drop('year', axis=1)

In [40]:
recommend_system = ((genres_table*weight_table).sum(axis=1)/ weight_table.sum())
recommend_system = recommend_system.sort_values(ascending=False)

In [49]:
recommend = movies.loc[movies.movieId.isin(recommend_system.head(20).keys())].reset_index()
recommend

,index,movieId,title,genres,year,Adventure,Animation,Children,Comedy,Fantasy,...,Horror,Mystery,Sci-Fi,IMAX,Documentary,War,Musical,Western,Film-Noir,(no genres listed)
0,0,1,Toy Story,"['Adventure', 'Animation', 'Children', 'Comedy...",1995,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2902,2987,Who Framed Roger Rabbit?,"['Adventure', 'Animation', 'Children', 'Comedy...",1988,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3028,3114,Toy Story 2,"['Adventure', 'Animation', 'Children', 'Comedy...",1999,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3664,3754,"Adventures of Rocky and Bullwinkle, The","['Adventure', 'Animation', 'Children', 'Comedy...",2000,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3923,4016,"Emperor's New Groove, The","['Adventure', 'Animation', 'Children', 'Comedy...",2000,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4212,4306,Shrek,"['Adventure', 'Animation', 'Children', 'Comedy...",2001,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,4791,4886,"Monsters, Inc.","['Adventure', 'Animation', 'Children', 'Comedy...",2001,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,8605,26093,"Wonderful World of the Brothers Grimm, The","['Adventure', 'Animation', 'Children', 'Comedy...",1962,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
8,8783,26340,"Twelve Tasks of Asterix, The (Les douze travau...","['Action', 'Adventure', 'Animation', 'Children...",1976,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,10120,33463,DuckTales: The Movie - Treasure of the Lost Lamp,"['Adventure', 'Animation', 'Children', 'Comedy...",1990,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,10375,36397,Valiant,"['Adventure', 'Animation', 'Children', 'Comedy...",2005,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
11,10997,45074,"Wild, The","['Adventure', 'Animation', 'Children', 'Comedy...",2006,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,11197,47124,"Ant Bully, The","['Adventure', 'Animation', 'Children', 'Comedy...",2006,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
13,12269,56152,Enchanted,"['Adventure', 'Animation', 'Children', 'Comedy...",2007,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
14,16770,84637,Gnomeo & Juliet,"['Adventure', 'Animation', 'Children', 'Comedy...",2011,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,18587,92348,Puss in Boots (Nagagutsu o haita neko),"['Adventure', 'Animation', 'Children', 'Comedy...",1969,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,21436,103755,Turbo,"['Adventure', 'Animation', 'Children', 'Comedy...",2013,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,22881,108932,The Lego Movie,"['Action', 'Adventure', 'Animation', 'Children...",2014,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,24273,114240,Aladdin,"['Adventure', 'Animation', 'Children', 'Comedy...",1992,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,24343,114552,"Boxtrolls, The","['Adventure', 'Animation', 'Children', 'Comedy...",2014,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0